### ISSUE TITLE
Docker compose version 2 file format breaks the http proxy

### ISSUE THREAD

**Issue by marclennox** [codekitchen/dinghy#135]
I tried switching to docker compose v2 file format, which has the services indented underneath a `services` key.  It appears that this breaks Dinghy's ability to expose virtual hosts using the http proxy container.

**Comment by codekitchen** [comment]
I haven't had a chance to look into this yet but I'm guessing it's related to nginx-proxy needing an upgrade (https://github.com/codekitchen/dinghy/issues/120)

**Comment by marclennox** [comment]
Seems strange though because the environment variables are being passed through just the same 

Sent from Outlook Mobile




On Tue, Feb 16, 2016 at 12:38 PM -0800, "Brian Palmer" <notifications@github.com> wrote:












I haven't had a chance to look into this yet but I'm guessing it's related to nginx-proxy needing an upgrade (#120)

**Comment by codekitchen** [comment]
The problem isn't with the env vars, it's because using a v2 compose file triggers compose to use docker's new networking layer, which nginx-proxy doesn't support yet.

https://github.com/jwilder/nginx-proxy/issues/362

Looks like there's a couple open PRs to fix this but none have been merged in yet. I'm not planning to work around this in Dinghy, I'd rather wait for the fix in nginx-proxy. Hopefully it doesn't take long.

**Comment by marclennox** [comment]
Ah right, this makes sense.  I remember reading something about docker no longer exposing environment variables in the new networking scheme, which a lot of containers rely on.

**Comment by marclennox** [comment]
Agreed though, no point fixing in dinghy!

**Comment by codekitchen** [comment]
Now that I've had some time to dig into the problem, I see that this will take some changes in dinghy even once nginx-proxy is fixed. The problem is we want our proxy to automatically work with any container that sets VIRTUAL_HOST, and docker-compose v2 now creates a private network for each app. So our proxy has to configure itself to join those private networks as necessary, so that it can reach the containers.

I think I have an idea on how to make this happen by writing a wrapper `-notify` script, but I doubt it'll be accepted into the upstream nginx-proxy project since it's not really their intended use case. I'll take a whack at it soon.

**Comment by codekitchen** [comment]
Support for this has landed on dinghy's master branch. I want to let it bake for a bit before releasing it, I need to test it out in more varied scenarios. You can try it out by installing the [dinghy prerelease](https://github.com/codekitchen/dinghy#prereleases), you should see the proxy using `codekitchen/dinghy-http-proxy:2.0.0` (version 2.0.0) in `docker ps`.

**Comment by marclennox** [comment]
Great stuff.  I just quickly tested it out.

It appears as though the proper configuration are being placed into the `/etc/nginx/conf.d/default.conf` however when I browse to any of the sites, I get the "Welcome to nginx on Debian!" page.

**Comment by codekitchen** [comment]
Hm interesting, that's the default "I don't know about the domain you gave me" page, which would imply the domain isn't in the config. Should be a `server_name <mydomain>.docker` block in the config. If you've confirmed that's in the config, maybe check for any errors in `/var/log/nginx/{error,access}.log` in the container?

**Comment by marclennox** [comment]
error.log is showing errors when nginx tried to reload the updated configuration.

`nginx: [emerg] no host in upstream ":9292" in /etc/nginx/conf.d/default.conf:28`

The line in question is in the upstream definition, and there's no host

```
upstream justreply.docker {
        server :9292;
}
```

**Comment by marclennox** [comment]
Note that all of the upstream definitions are without a host.

**Comment by codekitchen** [comment]
Ah that's definitely the problem thanks. I haven't seen that locally though, the logic is to grab the first exported address or network from each container, see https://github.com/codekitchen/dinghy-http-proxy/blob/master/nginx.tmpl#L46

Would it be possible to reduce your docker-compose.yml down to something you'd be comfortable pasting here? I bet a solid repro would make it easy to track down.

**Comment by codekitchen** [comment]
Never mind on that @marclennox , I found a repro in one of my local compose files. I'll fix it up.

**Comment by marclennox** [comment]
For sure, here's a pared down version that exhibits the issue.

```
version: '2'

volumes:
  postgresql_data:
    external: false
  rails_bundle:
    external: false

services:

  #
  # Volume container for all persisted data
  #
  volumes:
    image: tianon/true:latest
    volumes:
      - ..:/usr/src/app
      - postgresql_data:/data/postgresql
      - rails_bundle:/data/bundle

  #
  # Key-value database used for ephemeral storage and backs the sidekiq queues.
  # This is a required service to run the stack
  #
  redis_server:
    hostname: redis-server
    image: tenstartups/alpine-redis:latest

  #
  # Caching service not normally required in development unless specifically testing
  # centralized caching.
  #
  memcache_server:
    hostname: memcache-server
    image: tenstartups/alpine-memcached:latest

  #
  # Main database service that is required service to run the stack
  #
  postgresql_server:
    hostname: postresql-server
    environment:
      PGDATA: /data/postgresql
    image: postgres:latest
    volumes_from:
      - volumes

  #
  # Rails web server service that serves up all dynamic content and is required
  # to run the stack.
  #
  web_server:
    hostname: web-server
    environment:
      - VIRTUAL_HOST=justreply.docker
      - VIRTUAL_PORT=9292
      - RAILS_ENV
      - PRY_LISTEN_ADDRESS=web-server
      - PRY_LISTEN_PORT=9876
      - BUNDLE_APP_CONFIG=.bundle
      - BUNDLE_PATH=/data/bundle
      - ENV_FILE=config/application.env
    image: tenstartups/rails:latest
    command: web-server
    volumes_from:
      - volumes
    ports:
      - 9292 # Puma HTTP port
    links:
      - redis_server
      - memcache_server
      - postgresql_server
```
