### ISSUE TITLE
Strange output in default.conf when using docker-compose

### ISSUE THREAD

**Issue by envywebsites** [codekitchen/dinghy#238]
Hi there

I've been trying out the dingy http proxy in standalone, because I've just started out with Docker for Mac and it's great. I basically just wanted to reach a bunch of wordpress containers without having to manually change my /etc/hosts whenever I start a new project - and I work on several at any one time. So this does the job well!

The only snag I seem to have it, is that it only works for me when I specify the VIRTUAL_HOST in the env variables in docker-compose. If I omit that, the nginx conf file falls back to the auto-generated names.... but in my case, here's what I get:

```
upstream .wordpress.wordpress.docker {
	server 172.20.0.3:80;
}
server {
	server_name .wordpress.wordpress.docker;
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://.wordpress.wordpress.docker;
	}
}
```

(Note the stray . at the start of the server_name and location URL)

My docker-compose YAML looks like this:

```

version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data:
```

This obviously makes the containers completely unreachable by name unless I specify the hostname. 

Any idea what might be causing this behaviour?
