### ISSUE TITLE
[Question] bridge network and port mapping

### ISSUE THREAD

**Issue by jhoogeboom** [codekitchen/dinghy#283]
Normally docker-compose already bridges containers in the same service. It already opens all the ports to the other containers but not the host. So if you expose a container port in the Dockerfile, you can use the containername to address it. Does this methods apply to dinghy as well? That's what I thought, but perhaps I'm misunderstanding. I've setup dinghy with the default install & virtual box and made this test docker-compose:

```
version: "3.2"
services:
  redis:
    image: redis
    environment:
      VIRTUAL_HOST: redis.docker
      VIRTUAL_PORT: 6379
  crccheck:
    container_name: hello-world
    image: crccheck/hello-world
    environment:
      VIRTUAL_HOST: hello.docker
      VIRTUAL_PORT: 8000
  nginxdemo:
    image: nginxdemos/hello
    environment:
      VIRTUAL_HOST: nginx.docker
      VIRTUAL_PORT: 80
  ubuntu:
    container_name: ubuntu
    image: arunvelsriram/utils
```

Using `docker-compose run ubuntu bash` I can curl the Nginx.docker fine, somehow also fine on hello.docker using port 80, but not port 8000? only port 8000 is supposed to be exposed. testing Redis with `redis-cli -h redis.docker` is refused.

I try the same with `dinghy ssh`, same results.

But if I map the ports to the host (in this case the VM), or use the docker-compose 3.4 feature of `network_mode: host`, it works fine (although hello.docker is still also reachable from port 80, still remaining a mystery). Although now nginx won't be reachable anymore..

Is this intended behaviour or am I misunderstanding how dinghy is supposed to work?
