### ISSUE TITLE
question: ssh agent forwarding

### ISSUE THREAD

**Issue by rosskevin** [codekitchen/dinghy#82]
I'm having some problems getting ssh agent forwarding to work on OSX, wondering if there are any dinghy tricks to help.

Here is my setup:
http://stackoverflow.com/questions/32897709/ssh-agent-forwarding-inside-docker-compose-container

[This related comment](https://github.com/docker/compose/issues/551#issuecomment-118274489) states that virtualbox doesn't allow socket sharing.

```yaml
---
web:
  build: "."
  working_dir: "/project"
  ports:
  - '3000'
  environment:
  - SSH_AUTH_SOCK=/ssh-agent
  volumes:
  - "/private/tmp/com.apple.launchd.ZxGtZy6a9w/Listeners:/ssh-agent"
  command: bash -c "sleep 10 && echo 'foo' && exit 187"
```

If I run `docker-compose run web bash`, then `docker inspect ID`, I see 

```
        "Volumes": {
            "/project": {},
            "/ssh-agent": {}
        },
    "Mounts": [
        {
            "Source": "/private/tmp/com.apple.launchd.ZxGtZy6a9w/Listeners",
            "Destination": "/ssh-agent",
            "Mode": "rw",
            "RW": true
        },
        {
            "Name": "7ae8d939bd7ba0210a79fa14a3bb9a112a1b721525896533f3413c140d2a442f",
            "Source": "/mnt/sda1/var/lib/docker/volumes/7ae8d939bd7ba0210a79fa14a3bb9a112a1b721525896533f3413c140d2a442f/_data",
            "Destination": "/project",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
```

Any thoughts/tricks/tips?
