### ISSUE TITLE
Proxy is not allowing service to start

### ISSUE THREAD

**Issue by dyatlov** [codekitchen/dinghy#84]
When I run `docker-compose up`:

```
MBP-Vitaly:bb dyatlov$ docker-compose up
Starting bb_db_1...
Starting bb_web_1...
Cannot start container 473e51676f19ffa3e15245d6bc1ffb0e73b04b405ede41b9bcad1c7134ff8773: Bind for 0.0.0.0:80 failed: port is already allocated
```

My `docker-compose.yml`:

```yaml
db:
  image: postgres
web:
  build: .
  command: bundle exec foreman start -f Procfile
  volumes:
    - .:/app
  ports:
    - "80:3000"
    - "8030:8030"
  links:
    - db
  environment:
    - VIRTUAL_HOST=bb.dev
```

`Procfile`:

```ruby
rails: rails s -p 3000 -b '0.0.0.0'
webpack: npm start
```
